version: "3"
services:
	server:
		build: serveur_apache/
		container_name : Serveur_web
		command: 
		ports:
			- 1313:1313

	client:
		build: client/
		container_name: Client
		commande: python ./client.py
		network_mode: host
		depends_on:
			- server

	firewall:
		build: firewall/
		container_name: Firewall
		cap_add:
			- NET_ADMIN
		sysctls:
			- net.ipv4.ip_forward=1
		command: >
			bash -c "chmod -R +x . && ./clean.sh && ./firewall.sh

		depends_on:
			- client